spring:
    profiles:
        active: dev
server:
  port: 8385

swagger:
  title: 消息接口
  description: "业务方调用保存，前端调用展示"
  basePackage: com.sunlands.deskmate.web
  version: 1.0
  contact:
        name: 消息接口服务
        email: shixiaopeng@sunlands.com

springfox:
  documentation:
    swagger:
      v2:
        path: /doc #默认/v2/api-doc可能和应用接口命名冲突