spring:
  application:
    name: desk-mate-push
server:
  port: 8384

swagger:
  title: 极光push推送接口
  description: "给app推送push功能"
  basePackage: com.sunlands.deskmate.web
  version: 1.0
  contact:
        name: 石晓鹏
        email: shixiaopeng@sunlands.com

springfox:
  documentation:
    swagger:
      v2:
        path: /doc #默认/v2/api-doc可能和应用接口命名冲突

MASTER_SECRET: e72f3a8b4e9f546e7fc73154
APP_KEY: c831b758cbdf950ae4767711