eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://172.17.127.71:8761/eureka,http://172.17.127.72:8761/eureka,http://172.17.127.73:8761/eureka
    instance:
        hostname: localhost
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 3
        prefer-ip-address: true
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 3000
        wait-time-in-ms-when-sync-empty: 0

spring:
    datasource:
        url: jdbc:mysql://rm-2ze587km5m0ccrlmu.mysql.rds.aliyuncs.com:3306/zlcx_tongzhuo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: tongzhuo
        password: tz20190513=-
        #连接池的配置信息
        initialSize: 10
        minIdle: 3
        maxActive: 100
        maxWait: 60000
        validationQueryTimeout: 30
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 22
        host: r-2zed8ab56d8f15b4.redis.rds.aliyuncs.com
        port: 6379
        password: Sunlands2017      # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）

queue: hsk_queue_pro

security:
   oauth2:
     resource:
       token-info-uri: http://172.17.127.119:9666/oauth/check_token
     client:
       client-id: message
       client-secret: 123456
       access-token-uri: http://172.17.127.119:9666/oauth/token

ribbon:
  ReadTimeout: 20000
