
server:
    port: 8081

spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    application:
      name: desk-mate-socket

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis-config.xml
    typeAliasesPackage: com.sunlands.deskmate.*

netty:
    port: 9961
swagger:
  title: 聊天信息处理接口
  description: "聊天信息处理功能"
  basePackage: com.sunlands.deskmate.controller
  version: 1.0
  contact:
        name: 聊天信息处理接口服务
        email: liuyan@sunlands.com

springfox:
  documentation:
    swagger:
      v2:
        path: /doc #默认/v2/api-doc可能和应用接口命名冲突
