eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://sunlands:HL9i8gWoHuKLmEr9@172.16.0.7:8761/eureka/
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 3
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    server:
        enable-self-preservation: true
        eviction-interval-timer-in-ms: 3000
        wait-time-in-ms-when-sync-empty: 0 K

spring:
    datasource:
        url: jdbc:mysql://172.16.0.3:3306/zlcx_tongzhuo?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: zlcx_wx
        password: root456$%^
        #连接池的配置信息
        initialSize: 10
        minIdle: 3
        maxActive: 100
        maxWait: 60000
        validationQueryTimeout: 30
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
            open: true  # 是否开启redis缓存  true开启   false关闭
            database: 2
            host: 62.234.206.233
            port: 16379
            password: SunLands2018      # 密码（默认为空）
            timeout: 6000  # 连接超时时长（毫秒）

queue: hsk_queue_test


security:
  user:
    name: users
    password: 123456
  oauth2:
    resource:
      token-info-uri: http://localhost:9666/oauth/check_token
    client:
      client-id: users
      client-secret: 123456
      access-token-uri: http://localhost:9666/oauth/token
      grant-type: client_credentials