eureka:
    debug: true   #自定义参数，开始本地环境通过eurake调用test环境中的服务，
                  #设置为true开启，开启后将register-with-eureka配置参数设置为false,防止test环境调用到本地的微服务出错
    debug-url: https://tongzhuotest.sunlands.wang #测试环境注册微服务的真实访问路径，此配置适用于 同桌项目，其他项目根据情况配置
    client:
        fetch-registry: true
        register-with-eureka: false #本地使用时，将此属性设置为false，不会将本地服务注册到eurake上，但是本地服务可以从eurake上获取到服务信息
        service-url:
            defaultZone: http://sunlands:HL9i8gWoHuKLmEr9@62.234.206.233:8761/eureka/

spring:
    datasource:
        url: jdbc:mysql://bj-cdb-fmhcv6zw.sql.tencentcdb.com:62785/zlcx_tongzhuo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: zlcx_wx
        password: root456$%^
        #连接池的配置信息
        initialSize: 10
        minIdle: 3
        maxActive: 100
        maxWait: 60000
        validationQueryTimeout: 30
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
            open: true  # 是否开启redis缓存  true开启   false关闭
            database: 2
            host: 62.234.206.233
            port: 16379
            password: SunLands2018      # 密码（默认为空）
            timeout: 6000  # 连接超时时长（毫秒）

queue: hsk_queue_dev

security:
  oauth2:
    resource:
      token-info-uri: https://tongzhuotest.sunlands.wang/tz-user-center/oauth/check_token
    client:
      client-id: users
      client-secret: 123456
      access-token-uri: https://tongzhuotest.sunlands.wang/tz-user-center/oauth/token
      grant-type: client_credentials
