spring:
    datasource:
        url: jdbc:mysql://bj-cdb-fmhcv6zw.sql.tencentcdb.com:3306/zlcx_tongzhuo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: zlcx_wx
        password: root456$%^
        #连接池的配置信息
        initialSize: 10
        minIdle: 3
        maxActive: 100
        maxWait: 60000
        validationQueryTimeout: 30
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
            open: true  # 是否开启redis缓存  true开启   false关闭
            database: 2
            host: 62.234.206.233
            port: 16379
            password: SunLands2018      # 密码（默认为空）
            timeout: 6000  # 连接超时时长（毫秒）

queue: hsk_queue_test


security:
  user:
    name: users
    password: 123456
  oauth2:
    resource:
      token-info-uri: http://tongzhuotest.sunlands.wang/oauth/check_token
    client:
      client-id: users
      client-secret: 123456
      access-token-uri: http://tongzhuotest.sunlands.wang/oauth/token
      grant-type: client_credentials