eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        password: root456$%^
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:p6spy:mysql://bj-cdb-fmhcv6zw.sql.tencentcdb.com:62785/zlcx_tongzhuo?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: zlcx_wx
        tomcat:
          initial-size: 2
          max-active: 2
          min-idle: 2
          max-idle: 2
          test-on-borrow: true
    jpa:
        properties:
          hibernate:
                show_sql: false
    redis:
        database: 8
        host: 172.16.0.9
        password: SunLands2018
        pool:
            max-active: 600
            max-idle: 300
        port: 6379

message:
    type: 76