eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://sunlands:HL9i8gWoHuKLmEr9@172.16.0.7:8761/eureka/
    instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 3
        prefer-ip-address: true
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 3000
        wait-time-in-ms-when-sync-empty: 0
spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        tomcat:
          initial-size: 2
          max-active: 2
          min-idle: 2
          max-idle: 2
          test-on-borrow: true
        password: root456$%^
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:p6spy:mysql://172.16.0.3:3306/zlcx_tongzhuo?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: zlcx_wx
    jpa:
        properties:
            hibernate:
                show-sql: false
    redis:
        database: 8
        host: 172.16.0.9
        password: SunLands2018
        pool:
            max-active: 600
            max-idle: 300
        port: 6379
security:
   oauth2:
     resource:
       token-info-uri: http://localhost:9666/oauth/check_token
     client:
       client-id: message
       client-secret: 123456
       access-token-uri: http://localhost:9666/oauth/token
logging:
  level:
    org.springframework.security: info
    com.sunlands: DEBUG
ribbon:
  ReadTimeout: 20000

message:
    type: 76