eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://172.17.127.71:8761/eureka,http://172.17.127.72:8761/eureka,http://172.17.127.73:8761/eureka
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
        lease-expiration-duration-in-seconds: 10
        lease-renewal-interval-in-seconds: 5
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 3000
        wait-time-in-ms-when-sync-empty: 0
spring:
    datasource:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        druid:
            initial-size: 50
            max-active: 500
            max-wait: 60000
            min-idle: 50
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            validation-query: SELECT 'x'
        password: tz20190513=-
#        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:p6spy:mysql://rm-2ze587km5m0ccrlmu.mysql.rds.aliyuncs.com:3306/zlcx_tongzhuo?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        username: tongzhuo
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    redis:
        database: 22
        host: 172.17.69.178
        password: Sunlands2017
        pool:
            max-active: 600
            max-idle: 300
        port: 6379
security:
   oauth2:
     resource:
       token-info-uri: http://172.17.127.119:9666/oauth/check_token
     client:
       client-id: message
       client-secret: 123456
       access-token-uri: http://172.17.127.119:9666/oauth/token

ribbon:
  ReadTimeout: 20000

logging:
  level:
    org.springframework.security: INFO
    com.sunlands: INFO

message:
    type: 76